### ISSUE TITLE
failed in mjs file

### ISSUE THREAD

**Issue by JiangWeixian** [nodeca/js-yaml-js-types#4]
```ts
import yaml, { Type } from 'js-yaml'
import { all, regexp } from 'js-yaml-js-types'

console.log(regexp instanceof Type, typeof regexp, regexp)

const schema = yaml.DEFAULT_SCHEMA.extend(regexp);

const src = `
- !!js/regexp /pattern/g
- !!js/undefined ''
- !!js/function 'function () { return true }'
`

const parse = () => {
  console.log(yaml.load(src, { schema }))
}
```

get error

```plain
YAMLException: Schema.extend argument should be a Type, [ Type ], or a schema definition ({ implicit: [...], explicit: [...] })
```

and `regexp instanceof Type` is `false`

**Comment by puzrin** [comment]
This is commonjs module.

**Comment by ShaMan123** [comment]
@puzrin why should that matter?

https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c974790a30a89e456007d62976/package.json#L31

**Comment by ShaMan123** [comment]
I would expect that using a build tool such as rollup would make this work.
After inspecting the build I see that `Type` seems to be built twice so `instanceof` assertions fail
`type$1 instaceof type$2 === false`

**Comment by ShaMan123** [comment]
I suspect that when I import `js-yaml` it uses the dist files and when I import this package it uses the `index` file of `js-yaml`
Then I have 2 definitions of the same `Type` prototype

**Comment by ShaMan123** [comment]
confirmed by copying the source code and changing to imports.
this issue should be opened

**Comment by ShaMan123** [comment]
seems that build tools (rollup) fail in this case
tried `node-resolve` config with no success

**Comment by ShaMan123** [comment]
https://github.com/rollup/plugins/issues/1275
